services:
  mariadb:
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql:rw
      - ./docker/mariadb/init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
